### ISSUE TITLE
[ENH] - Nebari visual identity

### ISSUE THREAD

**Issue by trallard** [nebari-dev/nebari-design#2]
## Tasks

- [x] Put together a set of requirements for logo and design assets
- [x] Sync with design to get assets created
- [x] Align with website see nebari-dev/nebari-docs#182 
- [x] Align documentation theme
- [x] Publish guidelines and assets in this repo
